spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      maximum-pool-size: 200
      minimum-idle: 50
      driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver